import './globals.css'
import { Pirata_One } from 'next/font/google'

const inter = Pirata_One({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Landing Page Practice 1',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
